# -*- coding: utf-8 -*-
"""octanet python code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5zaL5z-N98QWMHPNH17Hjt69MDwx7A4
"""

class ATM:
    def __init__(self, username, password, initial_balance=0):
        self.username = username
        self.password = password
        self.balance = initial_balance

    def authenticate(self):
        entered_username = input("Enter your username: ")
        entered_password = input("Enter your password: ")
        return entered_username == self.username and entered_password == self.password

    def check_balance(self):
        print(f"Your current balance is: ${self.balance:.2f}")

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print(f"You have deposited: ${amount:.2f}")
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        if amount > 0:
            if amount <= self.balance:
                self.balance -= amount
                print(f"You have withdrawn: ${amount:.2f}")
            else:
                print("Insufficient funds.")
        else:
            print("Withdrawal amount must be positive.")

def main():
    atm = ATM("user123", "pass2029", 1000)  # Username: user123, Password: pass2029, Initial balance: $1000

    print("Welcome to the ATM!")
    if not atm.authenticate():
        print("Authentication failed. Exiting...")
        return

    while True:
        print("\n1. Check Balance")
        print("2. Deposit Money")
        print("3. Withdraw Money")
        print("4. Exit")

        choice = input("Please choose an option (1-4): ")

        if choice == '1':
            atm.check_balance()
        elif choice == '2':
            amount = float(input("Enter amount to deposit: "))
            atm.deposit(amount)
        elif choice == '3':
            amount = float(input("Enter amount to withdraw: "))
            atm.withdraw(amount)
        elif choice == '4':
            print("Thank you for using the ATM. Goodbye!")
            break
        else:
            print("Invalid choice. Please select a valid option.")

if __name__ == "__main__":
    main()